### ISSUE TITLE
Unknown software exception (0x40000015) crash

### ISSUE THREAD

**Issue by tpoppins** [bsamseth/Goldfish#39]
This is from the 40/40 test for v1.13.0 where Goldfish did very well and had no problems except in this game. On replay the problem occurred twice at the same spot, and the second time I managed to grab the log. On the third replay the game was finally completed without errors.

This was done on my dual Xeon E5-2670, a 16-core Sandy bridge box, Win 7 x64 Pro SP1, Cute Chess x64 2019-01-28 dev build. Funny, when I replayed this game twice on this dual X5670 (a 12-core Westmere-EX box), where all software is the same, the problem didn't occur.

A thread on StackOverflow that could be relevant: [https://stackoverflow.com/questions/5115611/in-windows-does-the-exception-unknown-software-exception-0x40000015-occurred](https://stackoverflow.com/questions/5115611/in-windows-does-the-exception-unknown-software-exception-0x40000015-occurred)

PGN:
```
[Event "?"]
[Site "?"]
[Date "2019.04.19"]
[Round "?"]
[White "Goldfish 1.13.0 64-bit"]
[Black "Alarm 0.93.1"]
[Result "0-1"]
[ECO "B03"]
[GameDuration "00:13:15"]
[GameEndTime "2019-04-19T14:58:29.901 Eastern Daylight Time"]
[GameStartTime "2019-04-19T14:45:14.283 Eastern Daylight Time"]
[Opening "Alekhine's defense"]
[PlyCount "32"]
[Termination "abandoned"]
[TimeControl "40/1320"]
[Variation "Four pawns attack"]

1. e4 {book} Nf6 {book} 2. e5 {book} Nd5 {book} 3. d4 {book} d6 {book}
4. c4 {book} Nb6 {book} 5. f4 {book} dxe5 {book} 6. fxe5 {book} c5 {book}
7. dxc5 {+0.12/11 37s} Qxd1+ {+0.39/12 39s} 8. Kxd1 {+0.13/14 37s}
Bg4+ {+0.43/13 39s} 9. Nf3 {+0.23/14 37s} N6d7 {+0.65/12 39s}
10. h3 {+0.24/13 37s} Bxf3+ {+0.90/14 39s} 11. gxf3 {+0.36/13 37s}
Nxe5 {+0.90/14 39s} 12. f4 {-0.09/13 37s} Nec6 {+0.99/13 39s}
13. Nd2 {-0.36/13 37s} Na6 {+1.50/13 39s} 14. Nb3 {-0.39/13 37s}
O-O-O+ {+1.37/13 39s} 15. Ke2 {-0.50/13 37s} e5 {+1.37/13 39s}
16. fxe5 {-0.54/13 37s} Nxe5 {+1.78/12 39s, White disconnects} 0-1

```

debug log:
[goldfish-1130-crash-log.txt](https://github.com/bsamseth/Goldfish/files/3099307/goldfish-1130-crash-log.txt)

WER report:
```
Version=1
EventType=APPCRASH
EventTime=132001739089682706
ReportType=2
Consent=1
UploadTime=132001739090150707
ReportIdentifier=1dcfa672-62d5-11e9-8b6d-b0e74d36b866
IntegratorReportIdentifier=1dcfa671-62d5-11e9-8b6d-b0e74d36b866
Response.BucketId=1803698571
Response.BucketTable=335404235
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=Goldfish.v1.13.0.64bit.exe
Sig[1].Name=Application Version
Sig[1].Value=0.0.0.0
Sig[2].Name=Application Timestamp
Sig[2].Value=5cadeade
Sig[3].Name=Fault Module Name
Sig[3].Value=Goldfish.v1.13.0.64bit.exe
Sig[4].Name=Fault Module Version
Sig[4].Value=0.0.0.0
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=5cadeade
Sig[6].Name=Exception Code
Sig[6].Value=40000015
Sig[7].Name=Exception Offset
Sig[7].Value=000000000004678f
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=6.1.7601.2.1.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=3faa
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=3faa3c265b91d2d7cbba3b1a01490fe5
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=99df
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=99df6c5724fefc12ed0cd49fd7b987f6
UI[2]=C:\Program Files\ChessBase\Engines.x64\CCRL\Goldfish.v1.13.0.64bit.exe
UI[3]=Goldfish.v1.13.0.64bit.exe has stopped working
UI[4]=Windows can check online for a solution to the problem.
UI[5]=Check online for a solution and close the program
UI[6]=Check online for a solution later and close the program
UI[7]=Close the program
LoadedModule[0]=C:\Program Files\ChessBase\Engines.x64\CCRL\Goldfish.v1.13.0.64bit.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\system32\kernel32.dll
LoadedModule[3]=C:\Windows\system32\KERNELBASE.dll
LoadedModule[4]=C:\Windows\system32\msvcrt.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
State[1].Key=DataRequest
State[1].Value=Bucket=1803698571/nBucketTable=335404235/nResponse=1/n
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=Goldfish.v1.13.0.64bit.exe
AppPath=C:\Program Files\ChessBase\Engines.x64\CCRL\Goldfish.v1.13.0.64bit.exe

```

P.S. Gábor, one of our blitz testers, reports that the latest v1.13.0 exec solved the problem of not moving after several moves  out of the book under Arena in Win10.

**Comment by bsamseth** [comment]
I'll see if I can reproduce this and try to track it down. Sounds like it might be some sort of threading (timing)  issue, given that it happens only some of the time. So I suspect that will make it hard to pin down, but I'll give it a shot! Thanks for the detailed logs+info.

Glad to hear things seem to work as they should for the most part at least! Very fun for me to have Goldfish out in the wild - although it's currently getting beaten up badly in [73rd Amateur Series, Division 9](http://kirill-kryukov.com/chess/discussion-board/viewtopic.php?f=7&t=11039)!

**Comment by tpoppins** [comment]
No wonder, the lowest-rated opponent there looks to be ~100 Elo higher. Graham has probably many more engines (esp. various versions of the same engine, which I don't use) installed than I but I doubt his list has many U2100 entries.

[This](http://ccrl.chessdom.com/ccrl/4040/cgi/compare_engines.cgi?family=Goldfish&print=Rating+list&print=Results+table&print=LOS+table&print=Ponder+hit+table&print=Eval+difference+table&print=Comopp+gamenum+table&print=Overlap+table&print=Score+with+common+opponents) looks a lot more balanced, wouldn't you agree? :)

**Comment by bsamseth** [comment]
Closing this as the new version (not ready just yet) is a complete rewrite, and so this particular problem is no longer relevant. Never could quite track this down back then...
