### ISSUE TITLE
King distance penalty in winning endgames

### ISSUE THREAD

**Issue by Oliverans** [bsamseth/Goldfish#51]
Check the following game against my engine which yours eventually found mate in: https://lichess.org/qVrIvQEh/black

Perhaps a simple king distance penalty in clearly winning end games will help solving some more basic endgames :) So it doesn't just randomly stumble upon a branch leading to mate.

Something like:
 ```Golang
// Max of either distance by rank or by file; either way we close the distance
r2r1 := math.Abs(enemyKingRank - friendlyKingRank)
f2f1 := math.Abs(enemyKingFile - friendlyKingFile)

if whiteWithAdvantage {
	score = Max(r2r1, f2f1) * -kingDistancePenalty
} else {
	score = Max(r2r1, f2f1) * kingDistancePenalty
}
```

**Comment by bsamseth** [comment]
Yeah, it sure looks silly. I think it doesn’t randomly stumble into the right direction, but rather it’s random until endgame tables start to meaningfully filter the moves when the halfmove count increases enough. If I ever see the engine lose due to this, then I’ll definitely add something like this. Until then I don’t want more things to tune if I can help it, even if the engine «trolls» like this in won endgames. 

Anyways, thanks for the suggestion!

**Comment by Oliverans** [comment]
Sorry to bother with a question as well, but since you mentioned tuning...

I've not tuned my engine yet. Only slapped on a ton of evaluation functions
(I got big plans 😅). Did you write your own texel tuner or use some
software for it?

And was it a big gain elo wise?

Thanks for any answers
~O

Den tis 10 dec. 2024 kl 07:24 skrev Bendik Samseth ***@***.***

**Comment by bsamseth** [comment]
Tuning has been a little hit and miss for me. I've mostly relied on my own, where I made tuning parameters into UCI options and did something similar to [this](https://www.chessprogramming.org/Stockfish%27s_Tuning_Method). This has worked OK, but so far there's been more low hanging fruit that give larger improvements. Like introducing more pruning types, even if not optimally tuned. Anyways, good luck with your engine!

**Comment by Oliverans** [comment]
Thank you for the response.

Good luck to you too and have a merry xmas!

Den lör 14 dec. 2024 kl 15:27 skrev Bendik Samseth ***@***.***
